import { Injectable, signal } from '@angular/core';

export type Language = 'id' | 'en';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private readonly STORAGE_KEY = 'lang';
  
  // Read from localStorage or default to 'id'
  readonly currentLang = signal<Language>(
    (localStorage.getItem(this.STORAGE_KEY) as Language) || 'id'
  );

  // Dynamic translations dictionary
  private readonly dictionary: Record<Language, Record<string, string>> = {
    id: {
      // Navigasi Group
      'Dashboard': 'Dashboard',
      'Transaksi': 'Transaksi',
      'Data Master': 'Data Master',
      'Inventori': 'Inventori',
      'Laporan': 'Laporan',
      'Sistem': 'Sistem',

      // Navigasi Item
      'Penjualan / POS': 'Penjualan / POS',
      'Pembelian': 'Pembelian',
      'Piutang': 'Piutang',
      'Hutang': 'Hutang',
      'Produk': 'Produk',
      'Kategori': 'Kategori',
      'Satuan': 'Satuan',
      'Supplier': 'Supplier',
      'Pelanggan': 'Pelanggan',
      'Stok': 'Stok',
      'Pengeluaran': 'Pengeluaran',
      'Pengaturan': 'Pengaturan',
      'User': 'User',
      'Log Aktivitas': 'Log Aktivitas',

      // Header & Layout
      'Sistem Internal Toko Kelontong': 'Sistem Internal Toko Kelontong',
      'Keluar': 'Keluar',
      'Manajemen Toko': 'Manajemen Toko',
      'Buka Kasir (POS)': 'Buka Kasir (POS)',
      'owner': 'Pemilik',
      'admin': 'Admin',
      'cashier': 'Kasir',
      'Navigasi utama': 'Navigasi utama',
      'Toggle menu': 'Buka/Tutup Menu',
      'Tutup menu': 'Tutup menu',

      // Aksi & Tombol
      'Tutup': 'Tutup',
      'Batal': 'Batal',
      'Detail': 'Detail',
      'Batalkan': 'Batalkan',
      'Hapus': 'Hapus',
      'Simpan': 'Simpan',
      'Tambah': 'Tambah',

      // Teks Umum & Tabel (Common)
      'No': 'No',
      'Tanggal': 'Tanggal',
      'Total': 'Total',
      'Status': 'Status',
      'Aksi': 'Aksi',
      'Coba Lagi': 'Coba Lagi',
      'Cari...': 'Cari...',
      'Semua': 'Semua',
      'Hapus filter': 'Hapus filter',
      'Kembalian': 'Kembalian',
      'Dibayar': 'Dibayar',
      'Total Bersih': 'Total Bersih',
      'Catatan': 'Catatan',
      'produk': 'produk',
      'Ya': 'Ya',
      'Tidak': 'Tidak',

      // Menu Penjualan (sales-list)
      'Penjualan & Retur': 'Penjualan & Retur',
      'Pantau transaksi penjualan kasir (POS) serta kelola pengembalian barang (retur penjualan).': 'Pantau transaksi penjualan kasir (POS) serta kelola pengembalian barang (retur penjualan).',
      'Riwayat Penjualan': 'Riwayat Penjualan',
      'Retur Penjualan': 'Retur Penjualan',
      'Cari No. Transaksi...': 'Cari No. Transaksi...',
      'Semua Cara Bayar': 'Semua Cara Bayar',
      'No. Transaksi': 'No. Transaksi',
      'Kasir': 'Kasir',
      'Cara Bayar': 'Cara Bayar',
      'Dibatalkan': 'Dibatalkan',
      'Belum Ada Transaksi Penjualan': 'Belum Ada Transaksi Penjualan',
      'Buka POS': 'Buka POS',
      'Buka POS dan lakukan penjualan pertama Anda.': 'Buka POS dan lakukan penjualan pertama Anda.',
      'Daftar Barang Belanja': 'Daftar Barang Belanja',
      'Nama Barang': 'Nama Barang',
      'Harga': 'Harga',
      'Pajak': 'Pajak',
      'Diskon': 'Diskon',
      'Retur Barang Belanja': 'Retur Barang Belanja',
      'Batalkan Penjualan': 'Batalkan Penjualan',

      // Menu Pembelian (purchases-list)
      'Pembelian & Retur': 'Pembelian & Retur',
      'Kelola riwayat pembelian barang dari supplier serta pengembalian barang (retur pembelian).': 'Kelola riwayat pembelian barang dari supplier serta pengembalian barang (retur pembelian).',
      'Buat Pembelian': 'Buat Pembelian',
      'Riwayat Pembelian': 'Riwayat Pembelian',
      'Retur Pembelian': 'Retur Pembelian',
      'Cari No. Pembelian...': 'Cari No. Pembelian...',
      'Semua Supplier': 'Semua Supplier',
      'No. Pembelian': 'No. Pembelian',
      'Total Transaksi': 'Total Transaksi',
      'Status Bayar': 'Status Bayar',
      'Belum Ada Transaksi Pembelian': 'Belum Ada Transaksi Pembelian',
      'Catat transaksi pembelian barang masuk pertama Anda.': 'Catat transaksi pembelian barang masuk pertama Anda.',
      'Cara Pembayaran': 'Cara Pembayaran',
      'Status Transaksi': 'Status Transaksi',
      'Daftar Barang': 'Daftar Barang',
      'Harga Beli Satuan': 'Harga Beli Satuan',
      'Retur Barang ke Supplier': 'Retur Barang ke Supplier',
      'Batalkan Transaksi': 'Batalkan Transaksi',

      // Menu Pengeluaran (expenses-list)
      'Kelola biaya operasional, tagihan, dan pengeluaran toko lainnya.': 'Kelola biaya operasional, tagihan, dan pengeluaran toko lainnya.',
      'Tambah Pengeluaran': 'Tambah Pengeluaran',
      'Kelola Kategori': 'Kelola Kategori',
      'Kategori Pengeluaran': 'Kategori Pengeluaran',
      'Cari Pengeluaran...': 'Cari Pengeluaran...',
      'Jumlah': 'Jumlah',
      'Waktu Pembatalan': 'Waktu Pembatalan',
      'Alasan Pembatalan': 'Alasan Pembatalan',
      'Semua Kategori': 'Semua Kategori',
      'Tambah Kategori': 'Tambah Kategori',
      'Daftar Pengeluaran': 'Daftar Pengeluaran',
      'Belum Ada Data Pengeluaran': 'Belum Ada Data Pengeluaran',
      'Mulai catat biaya operasional toko dengan tombol di kanan atas.': 'Mulai catat biaya operasional toko dengan tombol di kanan atas.',
      'Cari kategori pengeluaran...': 'Cari kategori pengeluaran...',
      'Belum Ada Kategori': 'Belum Ada Kategori',
      'Mulai tambahkan kategori pengeluaran baru.': 'Mulai tambahkan kategori pengeluaran baru.',
      'Nama Kategori': 'Nama Kategori',
      'Deskripsi': 'Deskripsi',
      'Aktif': 'Aktif',
      'Nonaktif': 'Nonaktif',
      'Edit': 'Edit',
      'Deaktif': 'Deaktif',
      'Detail Pengeluaran': 'Detail Pengeluaran',
      'No Transaksi': 'No Transaksi',
      'Metode Pembayaran': 'Metode Pembayaran',
      'Catat Pengeluaran Baru': 'Catat Pengeluaran Baru',
      'Pilih Kategori': 'Pilih Kategori',
      'Jumlah (IDR) *': 'Jumlah (IDR) *',
      'Cash (Tunai)': 'Cash (Tunai)',
      'Catatan / Keterangan': 'Catatan / Keterangan',
      'Misal: Pembayaran listrik bulanan Juni': 'Misal: Pembayaran listrik bulanan Juni',
      'Menyimpan...': 'Menyimpan...',
      'Nama Kategori *': 'Nama Kategori *',
      'Contoh: Operasional, Inventaris, Listrik': 'Contoh: Operasional, Inventaris, Listrik',
      'Deskripsi singkat': 'Deskripsi singkat',
      'Deaktifkan Kategori': 'Deaktifkan Kategori',
      'Apakah Anda yakin ingin menonaktifkan kategori pengeluaran ini? Kategori nonaktif tidak dapat dipilih saat mencatat pengeluaran baru.': 'Apakah Anda yakin ingin menonaktifkan kategori pengeluaran ini? Kategori nonaktif tidak dapat dipilih saat mencatat pengeluaran baru.',
      'Ya, Deaktifkan': 'Ya, Deaktifkan',

      // Menu Stok & Opname (inventory-list)
      'Stok & Koreksi': 'Stok & Koreksi',
      'Kelola stok barang masuk/keluar, koreksi stok opname.': 'Kelola stok barang masuk/keluar, koreksi stok opname.',
      'Ringkasan Stok': 'Ringkasan Stok',
      'Mutasi Stok': 'Mutasi Stok',
      'Stok Opname': 'Stok Opname',
      'Cari Produk...': 'Cari Produk...',
      'Buat Opname': 'Buat Opname',
      'Hanya Stok Menipis': 'Hanya Stok Menipis',
      'Tidak Ada Data Ringkasan': 'Tidak Ada Data Ringkasan',
      'Tambahkan produk untuk memantau status stoknya di sini.': 'Tambahkan produk untuk memantau status stoknya di sini.',
      'Nama Produk': 'Nama Produk',
      'Nilai Stok': 'Nilai Stok',
      'Habis': 'Habis',
      'Menipis': 'Menipis',
      'Aman': 'Aman',
      'Semua Tipe': 'Semua Tipe',
      'Penjualan': 'Penjualan',
      'Retur Jual': 'Retur Jual',
      'Retur Beli': 'Retur Beli',
      'Koreksi Masuk': 'Koreksi Masuk',
      'Koreksi Keluar': 'Koreksi Keluar',
      'Saldo Awal': 'Saldo Awal',
      'Tidak Ada Data Mutasi': 'Tidak Ada Data Mutasi',
      'Belum ada aktivitas penambahan atau pengurangan stok produk.': 'Belum ada aktivitas penambahan atau pengurangan stok produk.',
      'Qty Masuk': 'Qty Masuk',
      'Qty Keluar': 'Qty Keluar',
      'Referensi': 'Referensi',
      'Semua Status': 'Semua Status',
      'Belum Ada Stock Opname': 'Belum Ada Stock Opname',
      'Mulai lakukan pencocokan stok fisik barang dengan sistem.': 'Mulai lakukan pencocokan stok fisik barang dengan sistem.',
      'Tanggal Opname': 'Tanggal Opname',
      'Jumlah Item': 'Jumlah Item',
      'Detail Stock Opname': 'Detail Stock Opname',
      'Tanggal Pembuatan': 'Tanggal Pembuatan',
      'Detail Rincian Produk': 'Detail Rincian Produk',
      'Fisik': 'Fisik',
      'Selisih': 'Selisih',
      'Posting (Terapkan Stok Fisik)': 'Posting (Terapkan Stok Fisik)',
      'Batalkan Draft Opname': 'Batalkan Draft Opname',
      'Tanggal Opname *': 'Tanggal Opname *',
      'Cari & Tambah Produk ke Daftar': 'Cari & Tambah Produk ke Daftar',
      'Daftar Barang Opname': 'Daftar Barang Opname',
      'Alasan selisih/catatan...': 'Alasan selisih/catatan...',
      'Simpan Draft': 'Simpan Draft',
      'Posting Stock Opname': 'Posting Stock Opname',
      'Apakah Anda yakin ingin melakukan posting stock opname? Tindakan ini akan secara resmi memperbarui kuantitas stok di sistem agar sama dengan jumlah fisik yang Anda laporkan dan mencatat mutasi stok penyesuaian.': 'Apakah Anda yakin ingin melakukan posting stock opname? Tindakan ini akan secara resmi memperbarui kuantitas stok di sistem agar sama dengan jumlah fisik yang Anda laporkan dan mencatat mutasi stok penyesuaian.',
      'Ya, Posting': 'Ya, Posting',
      'No. Opname': 'No. Opname',
      'Mulai Stock Opname Baru': 'Mulai Stock Opname Baru',
      'Edit Draft Stock Opname': 'Edit Draft Stock Opname',
      'Cari': 'Cari',
      'Produk tidak ditemukan.': 'Produk tidak ditemukan.',
      'Belum ada barang. Cari produk di atas untuk menambahkan.': 'Belum ada barang. Cari produk di atas untuk menambahkan.',

      // Menu Dashboard
      'Ringkasan Toko': 'Ringkasan Toko',
      'Pantau data penjualan, pengeluaran, pergerakan stok, dan log sistem secara real-time.': 'Pantau data penjualan, pengeluaran, pergerakan stok, dan log sistem secara real-time.',
      'âš¡ Buka POS Kasir': 'âš¡ Buka POS Kasir',
      'Memuat ringkasan toko...': 'Memuat ringkasan toko...',
      'Penjualan Hari Ini': 'Penjualan Hari Ini',
      'Transaksi POS': 'Transaksi POS',
      'Pengeluaran Hari Ini': 'Pengeluaran Hari Ini',
      'Beban operasional & kas keluar': 'Beban operasional & kas keluar',
      'Pembelian Hari Ini': 'Pembelian Hari Ini',
      'Kulakan barang masuk': 'Kulakan barang masuk',
      'Alert Persediaan': 'Alert Persediaan',
      'stok habis': 'stok habis',
      'menipis': 'menipis',
      'Akses Cepat': 'Akses Cepat',
      'Pintasan ke modul utama operasional toko.': 'Pintasan ke modul utama operasional toko.',
      'Kasir POS': 'Kasir POS',
      'Catat penjualan': 'Catat penjualan',
      'Daftar barang': 'Daftar barang',
      'Pergerakan barang': 'Pergerakan barang',
      'Analisis toko': 'Analisis toko',
      'Metode Pembayaran Kasir': 'Metode Pembayaran Kasir',
      'Rincian cara pembayaran terlaris hari ini.': 'Rincian cara pembayaran terlaris hari ini.',
      'Belum ada penjualan tercatat hari ini.': 'Belum ada penjualan tercatat hari ini.',
      'Aktivitas Audit Terbaru': 'Aktivitas Audit Terbaru',
      'Riwayat perubahan data penting oleh user toko.': 'Riwayat perubahan data penting oleh user toko.',
      'Belum ada log audit yang terdeteksi.': 'Belum ada log audit yang terdeteksi.',

      // Pencarian, Filter & Separator
      's/d': 's/d',
      'Cari No. Opname...': 'Cari No. Opname...',

      // Modal Void / Pembatalan
      'Batalkan Transaksi Penjualan': 'Batalkan Transaksi Penjualan',
      'Batalkan Transaksi Pembelian': 'Batalkan Transaksi Pembelian',
      'Batalkan Pengeluaran': 'Batalkan Pengeluaran',
      'Batalkan Stock Opname': 'Batalkan Stock Opname',
      'Alasan Pembatalan *': 'Alasan Pembatalan *',
      'Alasan pembatalan...': 'Alasan pembatalan...',
      'Masukkan alasan pembatalan...': 'Masukkan alasan pembatalan...',
      'Ya, Batalkan': 'Ya, Batalkan',
      'Memproses...': 'Memproses...',
      'Apakah Anda yakin ingin membatalkan pengeluaran ini? Tindakan ini akan mengembalikan data kas.': 'Apakah Anda yakin ingin membatalkan pengeluaran ini? Tindakan ini akan mengembalikan data kas.',
      'Apakah Anda yakin ingin membatalkan stock opname ini?': 'Apakah Anda yakin ingin membatalkan stock opname ini?',

      // Modal Konfirmasi Hapus (Confirmation Dialogs)
      'Hapus Data Permanen': 'Hapus Data Permanen',
      'Apakah Anda yakin ingin menghapus data ini secara permanen dari database? Tindakan ini tidak dapat dibatalkan dan akan memulihkan data stok produk terkait.': 'Apakah Anda yakin ingin menghapus data ini secara permanen dari database? Tindakan ini tidak dapat dibatalkan dan akan memulihkan data stok produk terkait.',
      'Ya, Hapus Permanen': 'Ya, Hapus Permanen',
      'Hapus Pengeluaran': 'Hapus Pengeluaran',
      'Apakah Anda yakin ingin menghapus data pengeluaran ini secara permanen? Catatan pengeluaran dan riwayat kas terkait akan terhapus sepenuhnya dari database.': 'Apakah Anda yakin ingin menghapus data pengeluaran ini secara permanen? Catatan pengeluaran dan riwayat kas terkait akan terhapus sepenuhnya dari database.',
      'Hapus Stock Opname Permanen': 'Hapus Stock Opname Permanen',
      'Apakah Anda yakin ingin menghapus data stock opname ini secara permanen dari database? Tindakan ini tidak dapat dibatalkan dan akan memulihkan data stok produk terkait jika stock opname sudah terposting.': 'Apakah Anda yakin ingin menghapus data stock opname ini secara permanen dari database? Tindakan ini tidak dapat dibatalkan dan akan memulihkan data stok produk terkait jika stock opname sudah terposting.',

      // Form Retur & Lainnya
      'Tanggal Retur *': 'Tanggal Retur *',
      'Alasan Retur *': 'Alasan Retur *',
      'Catatan Tambahan': 'Catatan Tambahan',
      'Keterangan pendukung (opsional)': 'Keterangan pendukung (opsional)',
      'Misal: Barang kedaluwarsa, Rusak/Cacat': 'Misal: Barang kedaluwarsa, Rusak/Cacat',
      'Misal: Barang rusak dari pengiriman, Salah produk, dll.': 'Misal: Barang rusak dari pengiriman, Salah produk, dll.',
      'Pilih Barang untuk Diretur': 'Pilih Barang untuk Diretur',
      'Pilih': 'Pilih',
      'Maks': 'Maks',
      'item': 'item',
      'Beli': 'Beli',
      'Qty Retur': 'Qty Retur',
      'Refund/Item': 'Refund/Item',
      'Harga/Item': 'Harga/Item',
      'Total Refund Diperkirakan': 'Total Refund Diperkirakan',
      'Total Retur Diperkirakan': 'Total Retur Diperkirakan',
      'Proses Retur': 'Proses Retur',

      // Products
      'Kelola daftar produk, harga, barcode, stok minimum, dan status aktif.': 'Kelola daftar produk, harga, barcode, stok minimum, dan status aktif.',
      'Cari SKU, Barcode, atau Nama...': 'Cari SKU, Barcode, atau Nama...',
      'Cari produk': 'Cari produk',
      'Filter Kategori': 'Filter Kategori',
      'Filter Status Aktif': 'Filter Status Aktif',
      'Belum Ada Produk': 'Belum Ada Produk',
      'Tambahkan data produk untuk memulai pencatatan stok dan POS.': 'Tambahkan data produk untuk memulai pencatatan stok dan POS.',
      'SKU': 'SKU',
      'Nama Produk *': 'Nama Produk *',
      'Contoh: Indomie Goreng Spesial': 'Contoh: Indomie Goreng Spesial',
      'Nama produk wajib diisi.': 'Nama produk wajib diisi.',
      'SKU (Stock Keeping Unit)': 'SKU (Stock Keeping Unit)',
      'Auto jika kosong': 'Auto jika kosong',
      'Contoh: 899...': 'Contoh: 899...',
      'Kategori *': 'Kategori *',
      'Kategori wajib dipilih.': 'Kategori wajib dipilih.',
      'Satuan *': 'Satuan *',
      'Satuan wajib dipilih.': 'Satuan wajib dipilih.',
      'Harga Beli (IDR) *': 'Harga Beli (IDR) *',
      'Harga beli minimal 0.': 'Harga beli minimal 0.',
      'Harga Jual (IDR) *': 'Harga Jual (IDR) *',
      'Harga jual minimal 0.': 'Harga jual minimal 0.',
      'Stok Minimum (Alert)': 'Stok Minimum (Alert)',
      'Stok Awal': 'Stok Awal',
      'Nonaktif (Tidak akan muncul di POS)': 'Nonaktif (Tidak akan muncul di POS)',
      'Hapus Produk': 'Hapus Produk',
      'Apakah Anda yakin ingin menghapus produk ': 'Apakah Anda yakin ingin menghapus produk ',
      '? Aksi ini menggunakan soft-delete dan tidak akan menghapus riwayat transaksi.': '? Aksi ini menggunakan soft-delete dan tidak akan menghapus riwayat transaksi.',
      'Ya, Hapus': 'Ya, Hapus',

      // Categories
      'Kelola kategori produk untuk pengelompokan barang toko.': 'Kelola kategori produk untuk pengelompokan barang toko.',
      'Cari nama kategori...': 'Cari nama kategori...',
      'Cari kategori': 'Cari kategori',
      'kategori': 'kategori',
      'Memuat kategori...': 'Memuat kategori...',
      'Belum ada kategori': 'Belum ada kategori',
      'Tidak ada hasil untuk pencarian ini.': 'Tidak ada hasil untuk pencarian ini.',
      'Mulai dengan menambahkan kategori pertama.': 'Mulai dengan menambahkan kategori pertama.',
      'Daftar kategori': 'Daftar kategori',
      'Nama': 'Nama',
      'Hapus Kategori': 'Hapus Kategori',
      'Contoh: Minuman, Snack, Sembako': 'Contoh: Minuman, Snack, Sembako',
      'Nama kategori wajib diisi.': 'Nama kategori wajib diisi.',
      'Keterangan singkat (opsional)': 'Keterangan singkat (opsional)',

      // Units
      'Kelola satuan ukuran produk (seperti Pcs, Box, Kg, Liter).': 'Kelola satuan ukuran produk (seperti Pcs, Box, Kg, Liter).',
      'Tambah Satuan': 'Tambah Satuan',
      'Cari nama atau singkatan satuan...': 'Cari nama atau singkatan satuan...',
      'Cari satuan': 'Cari satuan',
      'satuan': 'satuan',
      'Memuat satuan...': 'Memuat satuan...',
      'Belum ada satuan': 'Belum ada satuan',
      'Mulai dengan menambahkan satuan pertama.': 'Mulai dengan menambahkan satuan pertama.',
      'Daftar satuan': 'Daftar satuan',
      'Singkatan': 'Singkatan',
      'Hapus Satuan': 'Hapus Satuan',
      'Tambah Satuan Baru': 'Tambah Satuan Baru',
      'Ubah Satuan': 'Ubah Satuan',
      'Nama Satuan *': 'Nama Satuan *',
      'Contoh: Kilogram, Pieces, Dus': 'Contoh: Kilogram, Pieces, Dus',
      'Nama satuan wajib diisi.': 'Nama satuan wajib diisi.',
      'Singkatan *': 'Singkatan *',
      'Contoh: Kg, Pcs, Box': 'Contoh: Kg, Pcs, Box',
      'Singkatan wajib diisi.': 'Singkatan wajib diisi.',

      // Suppliers
      'Kelola daftar supplier / pemasok barang toko Anda.': 'Kelola daftar supplier / pemasok barang toko Anda.',
      'Tambah Supplier': 'Tambah Supplier',
      'Cari nama, kontak, atau alamat supplier...': 'Cari nama, kontak, atau alamat supplier...',
      'Cari supplier': 'Cari supplier',
      'supplier': 'supplier',
      'Memuat supplier...': 'Memuat supplier...',
      'Belum ada supplier': 'Belum ada supplier',
      'Mulai dengan menambahkan supplier pertama.': 'Mulai dengan menambahkan supplier pertama.',
      'Daftar supplier': 'Daftar supplier',
      'Kontak / Telp': 'Kontak / Telp',
      'Alamat': 'Alamat',
      'Hapus Supplier': 'Hapus Supplier',
      'Tambah Supplier Baru': 'Tambah Supplier Baru',
      'Ubah Supplier': 'Ubah Supplier',
      'Nama Supplier *': 'Nama Supplier *',
      'Contoh: PT. Sumber Makmur': 'Contoh: PT. Sumber Makmur',
      'Nama supplier wajib diisi.': 'Nama supplier wajib diisi.',
      'Nomor Telepon': 'Nomor Telepon',
      'Contoh: 08123456789': 'Contoh: 08123456789',
      'Alamat Lengkap': 'Alamat Lengkap',
      'Contoh: Jl. Merdeka No. 123': 'Contoh: Jl. Merdeka No. 123',

      // Status & Payment Methods (database values -> Indonesian)
      'Completed': 'Selesai',
      'Voided': 'Dibatalkan',
      'Posted': 'Dibuat',
      'Open': 'Buka',
      'Closed': 'Tutup',
      'Paid': 'Lunas',
      'Unpaid': 'Belum Lunas',
      'Partial': 'Sebagian',
      'Cash': 'Tunai',
      'Transfer': 'Transfer',
      'QRIS': 'QRIS',
      'DebitCard': 'Kartu Debit',
      'Other': 'Lain-lain',
      'Platform': 'Platform',
      'Kelola Toko': 'Kelola Toko',
      'sysadmin': 'Sys Admin',
      // SysAdmin Stores
      'Kelola dan pantau seluruh pendaftaran toko kelontong di dalam platform.': 'Kelola dan pantau seluruh pendaftaran toko kelontong di dalam platform.',
      'Registrasi Toko Baru': 'Registrasi Toko Baru',
      'Cari nama toko, alamat, atau no telepon...': 'Cari nama toko, alamat, atau no telepon...',
      'toko': 'toko',
      'Memuat data toko dari server...': 'Memuat data toko dari server...',
      'Toko Tidak Ditemukan': 'Toko Tidak Ditemukan',
      'Tidak ada data toko kelontong yang sesuai dengan kata kunci pencarian Anda.': 'Tidak ada data toko kelontong yang sesuai dengan kata kunci pencarian Anda.',
      'Informasi Toko': 'Informasi Toko',
      'Kontak & Alamat': 'Kontak & Alamat',
      'Tanggal Bergabung': 'Tanggal Bergabung',
      'Ditangguhkan': 'Ditangguhkan',
      'Ubah Profil Toko': 'Ubah Profil Toko',
      'Tangguhkan Toko': 'Tangguhkan Toko',
      'Aktifkan Toko': 'Aktifkan Toko',
      'Registrasi Toko & Akun Owner': 'Registrasi Toko & Akun Owner',
      'Daftarkan profil toko fisik baru sekaligus membuat akun Owner pertama.': 'Daftarkan profil toko fisik baru sekaligus membuat akun Owner pertama.',
      'Nama Toko': 'Nama Toko',
      'Nama Toko wajib diisi (Maks. 100 karakter).': 'Nama Toko wajib diisi (Maks. 100 karakter).',
      'No. Telepon Toko': 'No. Telepon Toko',
      'Valuta / Currency': 'Valuta / Currency',
      'Zona Waktu / Timezone': 'Zona Waktu / Timezone',
      'Footer Struk Kasir': 'Footer Struk Kasir',
      'Logo URL (Opsional)': 'Logo URL (Opsional)',
      'Informasi Akun Owner': 'Informasi Akun Owner',
      'Nama Lengkap Owner': 'Nama Lengkap Owner',
      'Nama Owner wajib diisi.': 'Nama Owner wajib diisi.',
      'Username Login': 'Username Login',
      'Username wajib diisi.': 'Username wajib diisi.',
      'Password Akun': 'Password Akun',
      'Password minimal 6 karakter.': 'Password minimal 6 karakter.',
      'Simpan & Daftarkan': 'Simpan & Daftarkan',
      'Ubah data identitas toko kelontong terpilih.': 'Ubah data identitas toko kelontong terpilih.',
      'Simpan Perubahan': 'Simpan Perubahan',
      'Apakah Anda yakin ingin menonaktifkan toko {0}? Semua akun user dari toko ini akan ikut terpengaruh.': 'Apakah Anda yakin ingin menonaktifkan toko {0}? Semua akun user dari toko ini akan ikut terpengaruh.',
      'Apakah Anda yakin ingin mengaktifkan toko {0}? Semua akun user dari toko ini akan ikut terpengaruh.': 'Apakah Anda yakin ingin mengaktifkan toko {0}? Semua akun user dari toko ini akan ikut terpengaruh.',
      'Gagal mendaftarkan toko baru.': 'Gagal mendaftarkan toko baru.',
      'Terjadi kesalahan sistem saat mendaftarkan toko.': 'Terjadi kesalahan sistem saat mendaftarkan toko.',
      'Gagal memperbarui profil toko.': 'Gagal memperbarui profil toko.',
      'Terjadi kesalahan saat memperbarui profil toko.': 'Terjadi kesalahan saat memperbarui profil toko.',
      'Gagal mengubah status toko.': 'Gagal mengubah status toko.',
      'Terjadi kesalahan saat mengubah status toko.': 'Terjadi kesalahan saat mengubah status toko.',
      'Toko berhasil diaktifkan.': 'Toko berhasil diaktifkan.',
      'Toko berhasil dinonaktifkan.': 'Toko berhasil dinonaktifkan.',
      'Terjadi kesalahan saat memuat data toko.': 'Terjadi kesalahan saat memuat data toko.',
      // SysAdmin Dashboard
      'Total Toko Terdaftar': 'Total Toko Terdaftar',
      'Toko': 'Toko',
      'Toko Aktif / Nonaktif:': 'Toko Aktif / Nonaktif:',
      'Akun Owner Terdaftar': 'Akun Owner Terdaftar',
      'Estimasi Owner / Toko:': 'Estimasi Owner / Toko:',
      '1 Owner': '1 Owner',
      'Volume Transaksi Global': 'Volume Transaksi Global',
      'Bulan Berjalan:': 'Bulan Berjalan:',
      'Juni 2026': 'Juni 2026',
      'Uptime Server & Sistem': 'Uptime Server & Sistem',
      'Status Koneksi DB:': 'Status Koneksi DB:',
      'Stabil': 'Stabil',
      'Analisis Metrik Platform': 'Analisis Metrik Platform',
      'Grafik pertumbuhan toko, pengguna, dan performa uptime sistem server.': 'Grafik pertumbuhan toko, pengguna, dan performa uptime sistem server.',
      'Pengguna': 'Pengguna',
      'Performa Sistem': 'Performa Sistem',
      'MEMUAT GRAFIK...': 'MEMUAT GRAFIK...',
      'Toko Baru': 'Toko Baru',
      '3 pendaftaran retail terbaru.': '3 pendaftaran retail terbaru.',
      // Users List
      'Kelola seluruh akun Owner dan Admin toko kelontong di platform.': 'Kelola seluruh akun Owner dan Admin toko kelontong di platform.',
      'Kelola akun admin/penjaga untuk toko Anda (Maksimal 3 admin aktif).': 'Kelola akun admin/penjaga untuk toko Anda (Maksimal 3 admin aktif).',
      'User berhasil diperbarui.': 'User berhasil diperbarui.',
      'Gagal menyimpan user.': 'Gagal menyimpan user.',
      'User berhasil ditambahkan.': 'User berhasil ditambahkan.',
      'Gagal menambahkan user.': 'Gagal menambahkan user.',
      'Password berhasil direset.': 'Password berhasil direset.',
      'Gagal mereset password.': 'Gagal mereset password.',
      'User berhasil dihapus.': 'User berhasil dihapus.',
      'Gagal menghapus user.': 'Gagal menghapus user.',
      'Toko ini sudah mencapai batas maksimum 3 admin penjaga aktif.': 'Toko ini sudah mencapai batas maksimum 3 admin penjaga aktif.',
      'User berhasil diaktifkan.': 'User berhasil diaktifkan.',
      'User berhasil dinonaktifkan.': 'User berhasil dinonaktifkan.',
      'Gagal mengubah status user.': 'Gagal mengubah status user.',
      'Gagal memuat data pengguna.': 'Gagal memuat data pengguna.',
      'Gagal memuat daftar toko.': 'Gagal memuat daftar toko.',
      // Users List Interface
      'Kelola Pengguna': 'Kelola Pengguna',
      'Cari User': 'Cari User',
      'Cari nama atau username...': 'Cari nama atau username...',
      'Filter Peran': 'Filter Peran',
      'Semua Peran': 'Semua Peran',
      'Peran': 'Peran',
      'Tanggal Dibuat': 'Tanggal Dibuat',
      'Nama Lengkap': 'Nama Lengkap',
      'Peran / Hak Akses': 'Peran / Hak Akses',
      'Penempatan Toko': 'Penempatan Toko',
      'Admin / Penjaga': 'Admin / Penjaga',
      'Rasio Keaktifan Toko': 'Rasio Keaktifan Toko',
      'Toko Aktif:': 'Toko Aktif:',
      'Keaktifan Toko': 'Keaktifan Toko',
      'Grafik pertumbuhan toko, pengguna, dan rasio keaktifan toko.': 'Grafik pertumbuhan toko, pengguna, dan rasio keaktifan toko.',
    },
    en: {
      // Navigasi Group
      'Dashboard': 'Dashboard',
      'Transaksi': 'Transactions',
      'Data Master': 'Master Data',
      'Inventori': 'Inventory',
      'Laporan': 'Reports',
      'Sistem': 'System',
      'Platform': 'Platform',
      'Kelola Toko': 'Manage Stores',
      'sysadmin': 'Sys Admin',

      // Navigasi Item
      'Penjualan / POS': 'Sales / POS',
      'Pembelian': 'Purchases',
      'Piutang': 'Receivables',
      'Hutang': 'Payables',
      'Produk': 'Products',
      'Kategori': 'Categories',
      'Satuan': 'Units',
      'Supplier': 'Suppliers',
      'Pelanggan': 'Customers',
      'Stok': 'Stock',
      'Pengeluaran': 'Expenses',
      'Pengaturan': 'Settings',
      'User': 'User',
      'Log Aktivitas': 'Activity Logs',

      // Header & Layout
      'Sistem Internal Toko Kelontong': 'Grocery Store Internal System',
      'Keluar': 'Logout',
      'Manajemen Toko': 'Store Management',
      'Buka Kasir (POS)': 'Open Cashier (POS)',
      'owner': 'Owner',
      'admin': 'Admin',
      'cashier': 'Cashier',
      'Navigasi utama': 'Main Navigation',
      'Toggle menu': 'Toggle Menu',
      'Tutup menu': 'Close Menu',

      // Aksi & Tombol
      'Tutup': 'Close',
      'Batal': 'Cancel',
      'Detail': 'Details',
      'Batalkan': 'Cancel',
      'Hapus': 'Delete',
      'Simpan': 'Save',
      'Tambah': 'Add',

      // Teks Umum & Tabel (Common)
      'No': 'No',
      'Tanggal': 'Date',
      'Total': 'Total',
      'Status': 'Status',
      'Coba Lagi': 'Try Again',
      'Cari...': 'Search...',
      'Semua': 'All',
      'Hapus filter': 'Clear Filters',
      'Dibayar': 'Paid',
      'Total Bersih': 'Net Total',
      'Catatan': 'Notes',
      'produk': 'products',
      'Ya': 'Yes',
      'Tidak': 'No',
      'Menampilkan': 'Showing',
      'sampai': 'to',
      'dari': 'of',
      'data': 'entries',
      'Sebelumnya': 'Previous',
      'Selanjutnya': 'Next',

      // Menu Penjualan (sales-list)
      'Penjualan & Retur': 'Sales & Returns',
      'Pantau transaksi penjualan kasir (POS) serta kelola pengembalian barang (retur penjualan).': 'Monitor cashier sales transactions (POS) and manage item returns (sales returns).',
      'Riwayat Penjualan': 'Sales History',
      'Retur Penjualan': 'Sales Returns',
      'Cari No. Transaksi...': 'Search Transaction No...',
      'Semua Cara Bayar': 'All Payment Methods',
      'No. Transaksi': 'Transaction No.',
      'Kasir': 'Cashier',
      'Cara Bayar': 'Payment Method',
      'Dibatalkan': 'Cancelled',
      'Belum Ada Transaksi Penjualan': 'No Sales Transactions Yet',
      'Belum Ada Retur Penjualan': 'No Sales Returns Yet',
      'Buka POS': 'Open POS',
      'Buka POS dan lakukan penjualan pertama Anda.': 'Open POS and make your first sale.',
      'Daftar Barang Belanja': 'Shopping Items List',
      'Nama Barang': 'Item Name',
      'Harga': 'Price',
      'Pajak': 'Tax',
      'Retur Barang Belanja': 'Return Shopping Items',
      'Batalkan Penjualan': 'Cancel Sale',
      'Buka POS / Kasir': 'Open POS / Cashier',
      'penjualan': 'sales',
      'retur': 'returns',
      'Umum': 'General',
      'Maks': 'Max',
      'Anda akan membatalkan penjualan': 'You are about to cancel this sale',
      'Stok barang akan dikembalikan ke posisi semula.': 'Item stock will be restored to its original state.',
      'Pilih': 'Select',
      'Selesai': 'Completed',

      // Menu Pembelian (purchases-list)
      'Pembelian & Retur': 'Purchases & Returns',
      'Kelola riwayat pembelian barang dari supplier serta pengembalian barang (retur pembelian).': 'Manage purchase history from suppliers and item returns (purchase returns).',
      'Buat Pembelian': 'Create Purchase',
      'Riwayat Pembelian': 'Purchase History',
      'Retur Pembelian': 'Purchase Returns',
      'Cari No. Pembelian...': 'Search Purchase No...',
      'Semua Supplier': 'All Suppliers',
      'Status Bayar': 'Payment Status',
      'Belum Ada Transaksi Pembelian': 'No Purchase Transactions Yet',
      'Catat transaksi pembelian barang masuk pertama Anda.': 'Record your first incoming goods purchase transaction.',
      'Status Transaksi': 'Transaction Status',
      'Daftar Barang': 'Item List',
      'Harga Beli Satuan': 'Unit Purchase Price',
      'Retur Barang ke Supplier': 'Return Items to Supplier',
      'Batalkan Transaksi': 'Cancel Transaction',
      'transaksi': 'transactions',
      'Memuat pembelian...': 'Loading purchases...',
      'No. Pembelian': 'Purchase No.',
      'Memuat retur pembelian...': 'Loading purchase returns...',
      'Belum Ada Retur Pembelian': 'No Purchase Returns Yet',
      'Transaksi retur pembelian barang ke supplier akan muncul di sini. Buka detail transaksi pembelian untuk memproses retur.': 'Purchase return transactions to supplier will appear here. Open purchase transaction details to process a return.',
      'No. Retur': 'Return No.',
      'Tanggal Retur': 'Return Date',
      'Total Retur': 'Total Return',
      'Detail Retur Pembelian': 'Purchase Return Details',
      'Total Pengembalian': 'Total Refund',
      'Barang yang Diretur': 'Returned Items',
      'Form Retur Pembelian': 'Purchase Return Form',
      'Pilih item, tentukan kuantitas, nilai refund, dan alasan retur.': 'Select items, determine quantity, refund value, and return reason.',
      'Misal: Barang rusak dari pengiriman, Salah produk, dll.': 'e.g., Items damaged during shipping, Wrong product, etc.',
      'Beli': 'Bought',
      'Anda akan membatalkan transaksi': 'You are about to cancel this transaction',
      'Stok barang akan berkurang kembali.': 'Item stock will be reduced.',
      'Buat Transaksi Pembelian': 'Create Purchase Transaction',
      'Catat barang masuk dari supplier untuk menambah stok dan inventaris toko Anda.': 'Record incoming goods from suppliers to increase your store stock and inventory.',
      'Kembali': 'Back',
      'Informasi Pembelian': 'Purchase Information',
      'Pilih Supplier *': 'Select Supplier *',
      '-- Pilih Supplier --': '-- Select Supplier --',
      'Tanggal Pembelian *': 'Purchase Date *',
      'Tambahkan Barang Ke Daftar': 'Add Items to List',
      'Pilih Barang': 'Select Product',
      '-- Cari Barang --': '-- Search Product --',
      'Jumlah (Qty)': 'Quantity (Qty)',
      'Harga Beli Satuan (IDR)': 'Unit Purchase Price (IDR)',
      'Tambah ke Daftar': 'Add to List',
      'Belum ada barang di daftar belanja.': 'No items in the shopping list yet.',
      'Potongan Harga / Diskon (IDR)': 'Price Cut / Discount (IDR)',
      'Metode Bayar': 'Payment Method',
      'Cash (Tunai)': 'Cash',
      'Lunas': 'Paid',
      'Belum Lunas': 'Unpaid',
      'Catatan pendukung (opsional)...': 'Supporting notes (optional)...',
      'Simpan Transaksi': 'Save Transaction',

      // Menu Pengeluaran (expenses-list)
      'Kelola biaya operasional, tagihan, dan pengeluaran toko lainnya.': 'Manage operational costs, bills, and other store expenses.',
      'Tambah Pengeluaran': 'Add Expense',
      'Kelola Kategori': 'Manage Categories',
      'Kategori Pengeluaran': 'Expense Category',
      'Cari Pengeluaran...': 'Search Expenses...',
      'Jumlah': 'Amount',
      'Waktu Pembatalan': 'Cancellation Time',
      'Semua Kategori': 'All Categories',
      'Daftar Pengeluaran': 'Expense List',
      'Belum Ada Data Pengeluaran': 'No Expense Data Yet',
      'Mulai catat biaya operasional toko dengan tombol di kanan atas.': 'Start recording store operational costs with the top-right button.',
      'Cari kategori pengeluaran...': 'Search expense categories...',
      'Belum Ada Kategori': 'No Categories Yet',
      'Mulai tambahkan kategori pengeluaran baru.': 'Start adding new expense categories.',
      'Nama Kategori': 'Category Name',
      'Deskripsi': 'Description',
      'Aktif': 'Active',
      'Nonaktif': 'Inactive',
      'Edit': 'Edit',
      'Deaktif': 'Deactivate',
      'Detail Pengeluaran': 'Expense Details',
      'No Transaksi': 'Transaction No',
      'Metode Pembayaran': 'Payment Method',
      'Catat Pengeluaran Baru': 'Record New Expense',
      'Pilih Kategori': 'Select Category',
      'Jumlah (IDR) *': 'Amount (IDR) *',
      'Catatan / Keterangan': 'Notes / Description',
      'Misal: Pembayaran listrik bulanan Juni': 'e.g., June monthly electricity payment',
      'Menyimpan...': 'Saving...',
      'Contoh: Operasional, Inventaris, Listrik': 'e.g., Operational, Inventory, Electricity',
      'Deskripsi singkat': 'Short description',
      'Deaktifkan Kategori': 'Deactivate Category',
      'Apakah Anda yakin ingin menonaktifkan kategori pengeluaran ini? Kategori nonaktif tidak dapat dipilih saat mencatat pengeluaran baru.': 'Are you sure you want to deactivate this expense category? Inactive categories cannot be selected when recording new expenses.',
      'Ya, Deaktifkan': 'Yes, Deactivate',

      // Menu Stok & Opname (inventory-list)
      'Stok & Koreksi': 'Stock & Correction',
      'Kelola stok barang masuk/keluar, koreksi stok opname.': 'Manage incoming/outgoing stock, correct stock take (opname).',
      'Ringkasan Stok': 'Stock Summary',
      'Mutasi Stok': 'Stock Movements',
      'Stok Opname': 'Stock Take',
      'Cari Produk...': 'Search Products...',
      'Buat Opname': 'Create Stock Take',
      'Hanya Stok Menipis': 'Low Stock Only',
      'Tidak Ada Data Ringkasan': 'No Summary Data',
      'Tambahkan produk untuk memantau status stoknya di sini.': 'Add products to monitor their stock status here.',
      'Nama Produk': 'Product Name',
      'Nilai Stok': 'Stock Value',
      'Habis': 'Out of Stock',
      'Menipis': 'Low Stock',
      'Aman': 'Safe',
      'Semua Tipe': 'All Types',
      'Penjualan': 'Sales',
      'Retur Jual': 'Sales Returns',
      'Retur Beli': 'Purchase Returns',
      'Koreksi Masuk': 'Inward Correction',
      'Koreksi Keluar': 'Outward Correction',
      'Saldo Awal': 'Starting Balance',
      'Tidak Ada Data Mutasi': 'No Movement Data',
      'Belum ada aktivitas penambahan atau pengurangan stok produk.': 'No product stock addition or reduction activities yet.',
      'Qty Masuk': 'Qty In',
      'Qty Keluar': 'Qty Out',
      'Referensi': 'Reference',
      'Semua Status': 'All Statuses',
      'Belum Ada Stock Opname': 'No Stock Take Yet',
      'Mulai lakukan pencocokan stok fisik barang dengan sistem.': 'Start matching physical item stock with the system.',
      'Tanggal Opname': 'Stock Take Date',
      'Jumlah Item': 'Item Count',
      'Detail Stock Opname': 'Stock Take Details',
      'Tanggal Pembuatan': 'Creation Date',
      'Detail Rincian Produk': 'Product Details Rincian',
      'Fisik': 'Physical',
      'Selisih': 'Difference',
      'Posting (Terapkan Stok Fisik)': 'Post (Apply Physical Stock)',
      'Batalkan Draft Opname': 'Cancel Draft Stock Take',
      'Tanggal Opname *': 'Stock Take Date *',
      'Cari & Tambah Produk ke Daftar': 'Search & Add Product to List',
      'Daftar Barang Opname': 'Stock Take Items List',
      'Alasan selisih/catatan...': 'Reason for difference/notes...',
      'Simpan Draft': 'Save Draft',
      'Posting Stock Opname': 'Post Stock Take',
      'Apakah Anda yakin ingin melakukan posting stock opname? Tindakan ini akan secara resmi memperbarui kuantitas stok di sistem agar sama dengan jumlah fisik yang Anda laporkan dan mencatat mutasi stok penyesuaian.': 'Are you sure you want to post this stock take? This action will officially update stock quantities in the system to match the physical count you reported and record penyesuaian stock movements.',
      'Ya, Posting': 'Yes, Post',
      'No. Opname': 'Stock Take No.',
      'Mulai Stock Opname Baru': 'Start New Stock Take',
      'Edit Draft Stock Opname': 'Edit Draft Stock Take',
      'Cari': 'Search',
      'Produk tidak ditemukan.': 'Product not found.',
      'Belum ada barang. Cari produk di atas untuk menambahkan.': 'No items yet. Search products above to add.',

      // Menu Dashboard
      'Ringkasan Toko': 'Store Summary',
      'Pantau data penjualan, pengeluaran, pergerakan stok, dan log sistem secara real-time.': 'Monitor sales, expenses, stock movements, and system logs in real-time.',
      '⚡ Buka POS Kasir': '⚡ Open Cashier POS',
      'Memuat ringkasan toko...': 'Loading store summary...',
      'Penjualan Hari Ini': 'Today\'s Sales',
      'Transaksi POS': 'POS Transactions',
      'Pengeluaran Hari Ini': 'Today\'s Expenses',
      'Beban operasional & kas keluar': 'Operational expenses & cash outflow',
      'Pembelian Hari Ini': 'Today\'s Purchases',
      'Kulakan barang masuk': 'Incoming stock purchase',
      'Alert Persediaan': 'Stock Alerts',
      'stok habis': 'out of stock',
      'menipis': 'low stock',
      'Akses Cepat': 'Quick Access',
      'Pintasan ke modul utama operasional toko.': 'Shortcuts to key store operations.',
      'Kasir POS': 'Cashier POS',
      'Catat penjualan': 'Record sales',
      'Daftar barang': 'Item list',
      'Pergerakan barang': 'Item movements',
      'Analisis toko': 'Store analysis',
      'Metode Pembayaran Kasir': 'Cashier Payment Methods',
      'Rincian cara pembayaran terlaris hari ini.': 'Details of best-selling payment methods today.',
      'Belum ada penjualan tercatat hari ini.': 'No sales recorded today.',
      'Aktivitas Audit Terbaru': 'Recent Audit Activities',
      'Riwayat perubahan data penting oleh user toko.': 'History of key data changes by store users.',
      'Belum ada log audit yang terdeteksi.': 'No audit logs detected.',

      // Pencarian, Filter & Separator
      's/d': 'to',
      'Cari No. Opname...': 'Search Stock Take No...',

      // Modal Void / Pembatalan
      'Batalkan Transaksi Penjualan': 'Cancel Sales Transaction',
      'Batalkan Transaksi Pembelian': 'Cancel Purchase Transaction',
      'Batalkan Pengeluaran': 'Cancel Expense',
      'Batalkan Stock Opname': 'Cancel Stock Take',
      'Alasan Pembatalan *': 'Cancellation Reason *',
      'Alasan pembatalan...': 'Cancellation reason...',
      'Masukkan alasan pembatalan...': 'Enter cancellation reason...',
      'Ya, Batalkan': 'Yes, Cancel',
      'Memproses...': 'Processing...',
      'Apakah Anda yakin ingin membatalkan pengeluaran ini? Tindakan ini akan mengembalikan data kas.': 'Are you sure you want to cancel this expense? This action will reverse cash data.',
      'Apakah Anda yakin ingin membatalkan stock opname ini?': 'Are you sure you want to cancel this stock take?',

      // Modal Konfirmasi Hapus (Confirmation Dialogs)
      'Hapus Data Permanen': 'Delete Data Permanently',
      'Apakah Anda yakin ingin menghapus data ini secara permanen dari database? Tindakan ini tidak dapat dibatalkan dan akan memulihkan data stok produk terkait.': 'Are you sure you want to permanently delete this data from the database? This action cannot be undone and will restore related product stock data.',
      'Ya, Hapus Permanen': 'Yes, Delete Permanently',
      'Hapus Pengeluaran': 'Delete Expense',
      'Apakah Anda yakin ingin menghapus data pengeluaran ini secara permanen? Catatan pengeluaran dan riwayat kas terkait akan terhapus sepenuhnya dari database.': 'Are you sure you want to permanently delete this expense data? The expense record and related cash history will be completely deleted from the database.',
      'Hapus Stock Opname Permanen': 'Delete Stock Take Permanently',
      'Apakah Anda yakin ingin menghapus data stock opname ini secara permanen dari database? Tindakan ini tidak dapat dibatalkan dan akan memulihkan data stok produk terkait jika stock opname sudah terposting.': 'Are you sure you want to permanently delete this stock take data from the database? This action cannot be undone and will restore related product stock data if the stock take has been posted.',

      // Dashboard new translations
      'Halo,': 'Hello,',
      'Ringkasan performa toko kelontong Anda hari ini.': 'Summary of your grocery store performance today.',
      'Volume Transaksi:': 'Transaction Volume:',
      'nota': 'receipts',
      'Estimasi Laba Kotor': 'Estimated Gross Profit',
      'Marjin Laba:': 'Profit Margin:',
      'Pengeluaran Operasional': 'Operational Expenses',
      'Pembelian Inventori:': 'Inventory Purchases:',
      'Stok Menipis': 'Low Stock',
      'Perlu Segera Restock': 'Needs Immediate Restock',
      'Periksa Detail': 'Check Details',
      'Stok Habis': 'Out of Stock',
      'Barang': 'Item(s)',
      'Stok 0 - Tidak Bisa Dijual': 'Stock 0 - Cannot Be Sold',
      'Kelola': 'Manage',
      'Transaksi Selesai': 'Completed Transactions',
      'Nota': 'Receipt(s)',
      'Kinerja Kasir Aktif': 'Active Cashier Performance',
      'Stabil': 'Stable',
      'Omset Shift Hari Ini': 'Today\'s Shift Turnover',
      'Jumlah penjualan shift Anda hari ini': 'Your sales count for today\'s shift',
      'Nota Tercetak': 'Receipts Printed',
      'Transaksi terlayani harian': 'Daily served transactions',
      'Item': 'Item(s)',
      'Harap lapor ke pemilik toko': 'Please report to the store owner',
      'Stok Habis (0)': 'Out of Stock (0)',
      'Barang tidak bisa discan': 'Items cannot be scanned',
      'Performa Omset Penjualan': 'Sales Revenue Performance',
      'Grafik dinamik analisis nilai transaksi penjualan.': 'Dynamic chart for sales transaction value analysis.',
      '7 Hari': '7 Days',
      '30 Hari': '30 Days',
      'Bulan Ini': 'This Month',
      'MEMUAT GRAFIK...': 'LOADING CHART...',
      'Proporsi transaksi kasir hari ini.': 'Cashier transaction proportion today.',
      'Tunai (Cash)': 'Cash',
      'Transfer Bank': 'Bank Transfer',
      'QRIS Digital': 'Digital QRIS',
      'Metode pembayaran': 'Payment method',
      'Tunai': 'Cash',
      'disarankan selalu diverifikasi jumlah laci fisiknya pada saat penutupan shift kasir.': 'is recommended to always verify its physical drawer amount during cashier shift closure.',
      'Aktivitas Terakhir': 'Recent Activities',
      'Belum ada log aktivitas terdeteksi hari ini.': 'No activity logs detected today.',
      'Transaksi Kasir Terbaru': 'Latest Cashier Transactions',
      'Belum ada transaksi penjualan yang dilayani hari ini.': 'No sales transactions served today.',
      'Navigasi Cepat': 'Quick Navigation',
      'POS Penjualan': 'Sales POS',
      'Buka kasir transaksi': 'Open cashier transaction',
      'Kelola Stok': 'Manage Stock',
      'Pantau mutasi stok toko': 'Monitor store stock movements',
      'Laporan Keuangan': 'Financial Reports',
      'Analisis rugi laba & omset': 'Profit loss & turnover analysis',
      'vs kemarin': 'vs yesterday',
      'vs bulan lalu': 'vs last month',
      'produk vs kemarin': 'products vs yesterday',
      'barang vs kemarin': 'items vs yesterday',
      'vs rata-rata shift': 'vs shift average',
      'nota vs rata-rata shift': 'receipts vs shift average',
      'Tetap vs kemarin': 'Unchanged vs yesterday',

      'Total Refund Diperkirakan': 'Estimated Refund Total',
      'Total Retur Diperkirakan': 'Estimated Return Total',
      'Proses Retur': 'Process Return',

      // Products
      'Kelola daftar produk, harga, barcode, stok minimum, dan status aktif.': 'Manage product lists, prices, barcodes, minimum stock, and active status.',
      'Cari SKU, Barcode, atau Nama...': 'Search SKU, Barcode, or Name...',
      'Cari produk': 'Search product',
      'Filter Kategori': 'Filter Category',
      'Filter Status Aktif': 'Filter Active Status',
      'Belum Ada Produk': 'No Products Yet',
      'Tambahkan data produk untuk memulai pencatatan stok dan POS.': 'Add product data to start recording stock and POS.',
      'SKU': 'SKU',
      'Nama Produk *': 'Product Name *',
      'Contoh: Indomie Goreng Spesial': 'e.g., Indomie Goreng Spesial',
      'Nama produk wajib diisi.': 'Product name is required.',
      'SKU (Stock Keeping Unit)': 'SKU (Stock Keeping Unit)',
      'Auto jika kosong': 'Auto if empty',
      'Contoh: 899...': 'e.g., 899...',
      'Kategori *': 'Category *',
      'Kategori wajib dipilih.': 'Category is required.',
      'Satuan *': 'Unit *',
      'Satuan wajib dipilih.': 'Unit is required.',
      'Harga Beli (IDR) *': 'Purchase Price (IDR) *',
      'Harga beli minimal 0.': 'Purchase price must be at least 0.',
      'Harga Jual (IDR) *': 'Selling Price (IDR) *',
      'Harga jual minimal 0.': 'Selling price must be at least 0.',
      'Stok Minimum (Alert)': 'Minimum Stock (Alert)',
      'Stok Awal': 'Initial Stock',
      'Nonaktif (Tidak akan muncul di POS)': 'Inactive (Will not show in POS)',
      'Hapus Produk': 'Delete Product',
      'Apakah Anda yakin ingin menghapus produk ': 'Are you sure you want to delete product ',
      '? Aksi ini menggunakan soft-delete dan tidak akan menghapus riwayat transaksi.': '? This action uses soft-delete and will not delete transaction history.',
      'Ya, Hapus': 'Yes, Delete',

      // Product Form Additions
      'SKU (Kode Barang)': 'SKU (Item Code)',
      'KOSONGKAN UNTUK AUTO-GENERATE': 'LEAVE EMPTY TO AUTO-GENERATE',
      'Barcode': 'Barcode',
      'Barcode Scan / Kode Barcode': 'Barcode Scan / Barcode Code',
      'Nama lengkap produk': 'Complete product name',
      'Kategori wajib diisi.': 'Category is required.',
      'Pilih Satuan': 'Select Unit',
      'Satuan wajib diisi.': 'Unit is required.',
      'Harga beli wajib diisi.': 'Purchase price is required.',
      'Harga jual wajib diisi.': 'Selling price is required.',
      'Stok Awal *': 'Initial Stock *',
      'Stok awal wajib diisi.': 'Initial stock is required.',
      'Batas Minim Stok *': 'Low Stock Threshold *',
      'Batas minimum stok wajib diisi.': 'Minimum stock limit is required.',

      // Missing description/keterangan fallbacks & placeholders
      'Keterangan pendukung (opsional)': 'Supporting notes (optional)',
      'Keterangan deskripsi kategori...': 'Category description...',
      'Keterangan deskripsi satuan...': 'Unit description...',
      'Keterangan tambahan (opsional), misal: Cicilan ke-2, Ref transfer, dll.': 'Additional notes (optional), e.g., 2nd installment, Transfer ref, etc.',
      'Keterangan laci kasir (opsional)...': 'Cash drawer notes (optional)...',
      'Catatan Tambahan': 'Additional Notes',
      'Nama Pelanggan': 'Customer Name',

      // Missing subtitles
      'Kelola daftar pelanggan terdaftar untuk pencatatan riwayat transaksi POS.': 'Manage registered customer list for POS transaction history records.',
      'Pantau saldo piutang pelanggan toko serta kelola penagihan & riwayat pembayarannya.': 'Monitor store customer receivable balances and manage billing & payment history.',
      'Pantau saldo hutang kulakan toko ke supplier serta kelola pelunasan & riwayat pembayarannya.': 'Monitor store purchase debt balances to suppliers and manage settlements & payment history.',
      'Catat dan kelola pengeluaran operasional toko (seperti listrik, gaji karyawan, sewa tempat).': 'Record and manage store operational expenses (such as electricity, employee salaries, rent).',
      'Kelola stok produk, mutasi barang, penyesuaian stok (opname), dan riwayat perubahan stok.': 'Manage product stock, item mutations, stock adjustments (takes), and stock change history.',
      'Pantau catatan aktivitas operasional sistem oleh pengguna / kasir secara real-time.': 'Monitor system operational activity logs by users / cashiers in real-time.',

      // Missing settings tabs
      'Pengaturan Toko': 'Store Settings',
      'Keamanan & Password': 'Security & Password',

      // Missing empty/no item messages
      'Mulai dengan membuat transaksi pembelian pertama Anda.': 'Start by creating your first purchase transaction.',
      'Daftar retur pembelian barang ke supplier akan muncul di sini.': 'The list of purchase returns to the supplier will appear here.',
      'Mulai dengan melayani pelanggan di POS / Kasir.': 'Start by serving customers at the POS / Cashier.',
      'Daftar pengembalian barang dari pelanggan akan muncul di sini.': 'The list of item returns from customers will appear here.',

      // Missing form titles
      'Edit Produk': 'Edit Product',
      'Ubah Kategori': 'Edit Category',
      'Tambah Kategori Baru': 'Add New Category',

      // Inventory additions
      'Stok Toko Kosong': 'Store Stock Empty',
      'Tidak ada produk yang tercatat atau seluruh stok produk saat ini kosong.': 'No products are recorded or all product stock is currently empty.',
      'Silakan tambahkan data produk baru di menu Produk atau lakukan pembelian untuk mengisi stok.': 'Please add new product data in the Products menu or make a purchase to fill the stock.',
      'Koreksi': 'Correction',

      // Reports additions
      'siEntong - Laporan Manajemen Toko': 'siEntong - Store Management Report',
      'Cari Produk': 'Search Product',
      'Nama produk...': 'Product name...',
      'Dari Tanggal': 'From Date',
      'Gagal memuat laporan penjualan harian.': 'Failed to load daily sales report.',
      'Gagal memuat laporan penjualan produk.': 'Failed to load product sales report.',
      'Gagal memuat laporan valuasi stok.': 'Failed to load stock valuation report.',
      'Gagal memuat laporan laba rugi.': 'Failed to load profit & loss report.',
      'Kesalahan memuat data.': 'Error loading data.',
      'Laporan berhasil diekspor.': 'Report successfully exported.',
      'Gagal mengekspor laporan.': 'Failed to export report.',
      'Laporan Penjualan per Produk': 'Product Sales Report',
      'Laporan Ringkasan Laba Rugi': 'Profit & Loss Summary Report',
      'Laporan Toko': 'Store Reports',
      'Periode Laporan:': 'Report Period:',
      'Lihat performa penjualan, valuasi stok, dan ringkasan laba rugi toko.': 'View store sales performance, stock valuation, and profit & loss summary.',
      'Penjualan Produk': 'Product Sales',
      'Ringkasan Laba': 'Profit Summary',
      'Mengekspor...': 'Exporting...',
      'Ekspor PDF': 'Export PDF',
      'Tidak ada data penjualan harian': 'No daily sales data',
      'Sesuaikan filter tanggal untuk mencari data transaksi.' : 'Adjust the date filters to search for transaction data.',
      'Penjualan Kotor': 'Gross Sales',
      'Total Potongan': 'Total Discount',
      'Penjualan Bersih': 'Net Sales',
      'Tidak ada data penjualan produk': 'No product sales data',
      'Estimasi HPP': 'Estimated COGS',
      'Pencarian Tidak Ditemukan': 'Search Not Found',
      'Tidak ada produk yang cocok dengan kata kunci atau kategori tersebut.': 'No products match the keywords or category.',
      'Tidak ada data valuasi stok': 'No stock valuation data',
      'Coba cari nama produk yang lain.': 'Try searching for another product name.',
      'Harga Beli': 'Purchase Price',
      'Nilai Aset': 'Asset Value',
      'Tidak ada data performa laba': 'No profit performance data',
      'Harga Pokok Penjualan (HPP)': 'Cost of Goods Sold (COGS)',
      'Total Pengeluaran': 'Total Expenses',
      'Estimasi Laba Bersih': 'Estimated Net Profit',

      // Expenses additions
      'Catat biaya operasional toko seperti listrik, sewa, gaji karyawan, dan pengeluaran kas lainnya.': 'Record store operational expenses such as electricity, rent, employee salaries, and other cash expenses.',
      'Memuat data pengeluaran...': 'Loading expense data...',
      'No. Pengeluaran': 'Expense No.',
      'Jumlah (Amount)': 'Amount',
      'Void': 'Void',
      'Contoh: Operasional, Listrik, Gaji': 'e.g., Operational, Electricity, Salary',
      'Detail Pembatalan:': 'Void Details:',
      'Alasan': 'Reason',
      'Batalkan Pengeluaran (Void)': 'Cancel Expense (Void)',
      'Tanggal Pengeluaran *': 'Expense Date *',
      'Kategori Pengeluaran *': 'Expense Category *',
      'Metode Pembayaran *': 'Payment Method *',
      'Misal: Pembayaran listrik bulanan Juni...': 'e.g., Monthly electricity bill for June...',
      'Keterangan singkat': 'Short description',
      'Deskripsi kategori...': 'Category description...',
      'Anda akan membatalkan pengeluaran': 'You are about to cancel expense',
      'sebesar': 'for',
      'Tindakan ini tidak dapat diurungkan.': 'This action cannot be undone.',
      'Alasan Pembatalan': 'Void Reason',
      'Ya, Batalkan (Void)': 'Yes, Cancel (Void)',
      'Hapus Kategori Pengeluaran': 'Delete Expense Category',
      'Apakah Anda yakin ingin menghapus kategori': 'Are you sure you want to delete category',

      // Categories
      'Kelola kategori produk untuk pengelompokan barang toko.': 'Manage product categories for store item grouping.',
      'Tambah Kategori': 'Add Category',
      'Cari nama kategori...': 'Search category name...',
      'Cari kategori': 'Search category',
      'kategori': 'category(ies)',
      'Memuat kategori...': 'Loading categories...',
      'Belum ada kategori': 'No categories yet',
      'Tidak ada hasil untuk pencarian ini.': 'No results for this search.',
      'Mulai dengan menambahkan kategori pertama.': 'Start by adding the first category.',
      'Daftar kategori': 'Category list',
      'Nama': 'Name',
      'Hapus Kategori': 'Delete Category',
      'Nama Kategori *': 'Category Name *',
      'Contoh: Minuman, Snack, Sembako': 'e.g., Drinks, Snacks, Groceries',
      'Nama kategori wajib diisi.': 'Category name is required.',
      'Keterangan singkat (opsional)': 'Short description (optional)',

      // Units
      'Kelola satuan ukuran produk (seperti Pcs, Box, Kg, Liter).': 'Manage product measurement units (like Pcs, Box, Kg, Liter).',
      'Tambah Satuan': 'Add Unit',
      'Cari nama atau singkatan satuan...': 'Search unit name or abbreviation...',
      'Cari satuan': 'Search unit',
      'satuan': 'unit(s)',
      'Memuat satuan...': 'Loading units...',
      'Belum ada satuan': 'No units yet',
      'Mulai dengan menambahkan satuan pertama.': 'Start by adding the first unit.',
      'Daftar satuan': 'Unit list',
      'Singkatan': 'Abbreviation',
      'Hapus Satuan': 'Delete Unit',
      'Tambah Satuan Baru': 'Add New Unit',
      'Ubah Satuan': 'Edit Unit',
      'Nama Satuan *': 'Unit Name *',
      'Contoh: Kilogram, Pieces, Dus': 'e.g., Kilogram, Pieces, Box',
      'Nama satuan wajib diisi.': 'Unit name is required.',
      'Singkatan *': 'Abbreviation *',
      'Contoh: Kg, Pcs, Box': 'e.g., Kg, Pcs, Box',
      'Singkatan wajib diisi.': 'Abbreviation is required.',

      // Suppliers
      'Kelola daftar supplier / pemasok barang toko Anda.': 'Manage your store\'s supplier/vendor list.',
      'Kelola daftar supplier tempat pembelian produk stok toko Anda.': 'Manage supplier list for purchasing your store\'s product stock.',
      'Tambah Supplier': 'Add Supplier',
      'Cari nama, kontak, atau alamat supplier...': 'Search supplier name, contact, or address...',
      'Cari supplier': 'Search supplier',
      'supplier': 'supplier(s)',
      'Memuat supplier...': 'Loading suppliers...',
      'Belum ada supplier': 'No suppliers yet',
      'Belum Ada Supplier': 'No Suppliers Yet',
      'Mulai dengan menambahkan supplier pertama.': 'Start by adding the first supplier.',
      'Mulai dengan menambahkan supplier pertama Anda.': 'Start by adding your first supplier.',
      'Daftar supplier': 'Supplier list',
      'Kontak / Telp': 'Contact / Phone',
      'Alamat': 'Address',
      'Hapus Supplier': 'Delete Supplier',
      'Tambah Supplier Baru': 'Add New Supplier',
      'Ubah Supplier': 'Edit Supplier',
      'Nama Supplier *': 'Supplier Name *',
      'Contoh: PT. Sumber Makmur': 'e.g., PT. Sumber Makmur',
      'Nama supplier wajib diisi.': 'Supplier name is required.',
      'Nomor Telepon': 'Phone Number',
      'Contoh: 08123456789': 'e.g., 08123456789',
      'Alamat Lengkap': 'Full Address',
      'Contoh: Jl. Merdeka No. 123': 'e.g., Merdeka St No. 123',

      // Customers
      'Kelola data pelanggan toko untuk pencatatan transaksi kasir.': 'Manage store customer data for cashier transaction records.',
      'Tambah Pelanggan': 'Add Customer',
      'Cari nama atau telepon pelanggan...': 'Search customer name or phone...',
      'Cari pelanggan': 'Search customer',
      'pelanggan': 'customer(s)',
      'Memuat pelanggan...': 'Loading customers...',
      'Belum ada pelanggan': 'No customers yet',
      'Belum Ada Pelanggan': 'No Customers Yet',
      'Mulai dengan menambahkan pelanggan pertama.': 'Start by adding the first customer.',
      'Mulai dengan menambahkan pelanggan pertama Anda.': 'Start by adding your first customer.',
      'Daftar pelanggan': 'Customer list',
      'Hapus Pelanggan': 'Delete Customer',
      'Tambah Pelanggan Baru': 'Add New Customer',
      'Ubah Pelanggan': 'Edit Customer',
      'Nama Pelanggan *': 'Customer Name *',
      'Contoh: Budi Santoso': 'e.g., Budi Santoso',
      'Nama pelanggan wajib diisi.': 'Customer name is required.',

      // Settings
      'Pengaturan Toko & Operasional': 'Store Settings & Operations',
      'Kelola profil toko, kebijakan stok, dan konfigurasi POS Kasir.': 'Manage store profile, stock policies, and POS Cashier configuration.',
      'Profil Toko': 'Store Profile',
      'Kebijakan Stok & Transaksi': 'Stock & Transaction Policies',
      'Simpan Pengaturan': 'Save Settings',

      // Settings toast additions
      'Gagal mengambil profil toko.': 'Failed to fetch store profile.',
      'Gagal mengambil pengaturan toko.': 'Failed to fetch store settings.',
      'Profil toko berhasil diperbarui.': 'Store profile updated successfully.',
      'Gagal memperbarui profil toko.': 'Failed to update store profile.',
      'Terjadi kesalahan saat memperbarui profil toko.': 'An error occurred while updating store profile.',
      'Pengaturan toko berhasil diperbarui.': 'Store settings updated successfully.',
      'Gagal memperbarui pengaturan toko.': 'Failed to update store settings.',
      'Terjadi kesalahan saat memperbarui pengaturan toko.': 'An error occurred while updating store settings.',
      'Password Anda berhasil diubah.': 'Your password has been changed successfully.',
      'Gagal mengubah password.': 'Failed to change password.',
      'Password lama Anda salah atau terjadi kesalahan server.': 'Your old password is incorrect or a server error occurred.',
      'Nama Toko *': 'Store Name *',
      'Contoh: Toko Entong': 'e.g., Toko Entong',
      'Nama toko wajib diisi.': 'Store name is required.',
      'Telepon Toko': 'Store Phone',
      'Alamat Toko': 'Store Address',
      'Mata Uang': 'Currency',
      'Mata Uang *': 'Currency *',
      'Default: IDR (Rupiah)': 'Default: IDR (Rupiah)',
      'Izinkan Stok Negatif (Jual Melebihi Stok)': 'Allow Negative Stock (Sell Beyond Stock)',
      'Memungkinkan kasir checkout barang walaupun stok di sistem 0.': 'Allows cashier to checkout items even if system stock is 0.',
      'Wajibkan Sesi Kasir untuk Penjualan POS': 'Require Cashier Session for POS Sales',
      'POS hanya bisa diakses jika sesi kasir aktif telah dibuka.': 'POS can only be accessed if an active cashier session is opened.',
      'Default Batas Stok Menipis': 'Default Low Stock Threshold',
      'Batas default untuk trigger alert stok menipis pada produk.': 'Default limit to trigger low stock alert on products.',
      'Aktifkan Fitur Barcode Scanner': 'Enable Barcode Scanner Feature',
      'Aktifkan input barcode otomatis pada layar POS Kasir.': 'Enable automatic barcode input on POS Cashier screen.',
      'Lacak Riwayat Harga Beli Produk': 'Track Product Purchase Price History',
      'Simpan otomatis riwayat perubahan harga beli saat kulakan supplier.': 'Automatically save purchase price changes history during supplier restocking.',

      // Settings Labels & Descriptions Additions
      'Zona Waktu (Timezone) *': 'Timezone *',
      'Footer Struk Belanja': 'Receipt Footer',
      'Nama Toko wajib diisi dan maksimal 100 karakter.': 'Store Name is required and must be maximum 100 characters.',
      'Izinkan Stok Negatif': 'Allow Negative Stock',
      'Memperbolehkan penjualan barang meskipun stok sistem habis/nol.': 'Allow item checkout even if the system stock is out/zero.',
      'Memungkinkan pencarian barang menggunakan scanner barcode pada halaman penjualan.': 'Enables product search using a barcode scanner on the sales page.',
      'Lacak Harga Beli Produk': 'Track Product Purchase Price',
      'Mencatat riwayat harga beli dan menghitung estimasi keuntungan bersih.': 'Records purchase price history and calculates estimated net profit.',
      'Batas Minimum Stok Tipis (Threshold) *': 'Low Stock Warning Limit (Threshold) *',
      'Metode Pembayaran Utama *': 'Default Payment Method *',
      'Password Saat Ini *': 'Current Password *',
      'Password lama wajib diisi.': 'Current password is required.',
      'Password baru wajib diisi dan minimal 6 karakter.': 'New password is required and must be at least 6 characters.',
      'Konfirmasi Password Baru *': 'Confirm New Password *',
      'Ulangi password baru': 'Repeat new password',
      'Konfirmasi password tidak cocok dengan password baru.': 'Password confirmation does not match the new password.',

      // Users
      'Kelola akun pengguna, hak akses administrator/pemilik, dan reset password.': 'Manage user accounts, admin/owner access rights, and password resets.',
      'Tambah User': 'Add User',
      'Cari nama atau username user...': 'Search user name or username...',
      'Cari user': 'Search user',
      'user': 'user(s)',
      'Memuat user...': 'Loading users...',
      'Belum ada user': 'No users yet',
      'Mulai dengan menambahkan user pertama.': 'Start by adding the first user.',
      'Daftar user': 'User list',
      'Username': 'Username',
      'Role': 'Role',
      'Hapus User': 'Delete User',
      'Tambah User Baru': 'Add New User',
      'Ubah User': 'Edit User',
      'Nama Lengkap *': 'Full Name *',
      'Contoh: Admin Toko': 'e.g., Store Admin',
      'Nama lengkap wajib diisi.': 'Full name is required.',
      'Username *': 'Username *',
      'Contoh: admin123': 'e.g., admin123',
      'Username wajib diisi.': 'Username is required.',
      'Role / Hak Akses *': 'Role / Access Rights *',
      'Pilih Role': 'Select Role',
      'Role wajib dipilih.': 'Role is required.',
      'Password *': 'Password *',
      'Minimal 6 karakter': 'Min 6 characters',
      'Password wajib diisi.': 'Password is required.',
      'Password minimal 6 karakter.': 'Password must be at least 6 characters.',
      'Reset Password User': 'Reset User Password',
      'Password Baru *': 'New Password *',
      'Reset Password': 'Reset Password',

      // Audit Logs
      'Log Audit Sistem': 'System Audit Logs',
      'Pantau riwayat aktivitas perubahan data penting oleh pengguna sistem toko secara real-time.': 'Monitor history of changes to key data by store system users in real-time.',
      'Cari aktivitas log...': 'Search log activities...',
      'Semua Modul': 'All Modules',
      'Semua Aksi': 'All Actions',
      'log': 'log(s)',
      'Memuat log audit...': 'Loading audit logs...',
      'Belum ada log audit': 'No audit logs yet',
      'Tidak ada log aktivitas yang terekam pada periode ini.': 'No activity logs recorded in this period.',
      'Daftar log audit': 'Audit log list',
      'Waktu': 'Time',
      'Modul': 'Module',
      'Pengguna': 'User',
      'Detail Log Audit': 'Audit Log Details',
      'Deskripsi Aktivitas': 'Activity Description',
      'Detail Perubahan Data (Sebelum & Sesudah)': 'Data Changes Detail (Before & After)',
      'Data Sebelum': 'Data Before',
      'Data Sesudah': 'Data After',
      'Tidak ada rincian data mentah yang tercatat.': 'No raw data details recorded.',

      // Reports
      'Laporan Operasional Toko': 'Store Operational Reports',
      'Pantau kinerja penjualan, pembelian, laba kotor, beban pengeluaran, dan valuasi stok Anda.': 'Monitor performance of sales, purchases, gross profit, operational expenses, and stock valuation.',
      'Ekspor Excel': 'Export Excel',
      'Cetak PDF': 'Print PDF',
      'Periode:': 'Period:',
      'Penjualan Harian': 'Daily Sales',
      'Produk Terlaris': 'Best Sellers',
      'Valuasi Stok': 'Stock Valuation',
      'Laba Kotor': 'Gross Profit',
      'Laporan Penjualan Harian': 'Daily Sales Report',
      'Daftar total transaksi dan cara pembayaran per hari.': 'List of total transactions and payment methods per day.',
      'Laporan Penjualan Produk': 'Product Sales Report',
      'Daftar produk paling laku dan kontribusi omzet penjualan.': 'List of top selling products and revenue contributions.',
      'Laporan Valuasi Nilai Stok': 'Stock Valuation Report',
      'Nilai aset persediaan barang saat ini berdasarkan harga beli.': 'Current value of stock inventory based on purchase price.',
      'Laporan Laba / Rugi Kotor': 'Gross Profit & Loss Report',
      'Kalkulasi laba kotor dari omzet dikurangi harga pokok penjualan (HPP).': 'Calculation of gross profit from revenue minus cost of goods sold (COGS).',
      'Memuat laporan...': 'Loading report...',
      'Tidak ada data laporan untuk periode ini.': 'No report data for this period.',
      'Total Transaksi': 'Total Transactions',
      'Omzet Penjualan': 'Sales Revenue',
      'Qty Terjual': 'Qty Sold',
      'Nilai Persediaan': 'Inventory Value',
      'HPP': 'COGS',
      'Margin': 'Margin',

      // Receivables & Payables
      'Hutang & Piutang': 'Debts & Receivables',
      'Daftar Piutang Pelanggan': 'Customer Receivables List',
      'Pantau saldo piutang belanja pelanggan, tanggal jatuh tempo, dan kelola pembayaran.': 'Monitor customer receivable balances, due dates, and manage payments.',
      'Cari pelanggan...': 'Search customer...',
      'piutang': 'receivable(s)',
      'Memuat piutang...': 'Loading receivables...',
      'Belum Ada Piutang': 'No Receivables Yet',
      'Pelanggan Anda belum memiliki catatan piutang belanja.': 'Your customers do not have shopping receivable records yet.',
      'Jatuh Tempo': 'Due Date',
      'Sisa Piutang': 'Remaining Receivable',
      'Aksi': 'Actions',
      'Bayar': 'Pay',
      'Detail Piutang': 'Receivable Details',
      'Riwayat Pembayaran Piutang': 'Receivable Payment History',
      'Belum ada pembayaran dicatat untuk piutang ini.': 'No payment recorded for this receivable yet.',
      'Bayar Piutang': 'Pay Receivable',
      'Jumlah Bayar (IDR) *': 'Payment Amount (IDR) *',
      'Maksimal Sisa:': 'Max Remaining:',
      'Catatan Pembayaran': 'Payment Notes',
      'Misal: Bayar cicilan pertama': 'e.g., Pay first installment',
      'Hutang Supplier': 'Supplier Payables',
      'Pantau saldo hutang kulakan toko ke supplier, tanggal jatuh tempo, dan kelola pelunasan.': 'Monitor shop purchase debt balances to suppliers, due dates, and manage settlement.',
      'Cari supplier...': 'Search supplier...',
      'hutang': 'payable(s)',
      'Memuat hutang...': 'Loading payables...',
      'Belum Ada Hutang': 'No Payables Yet',
      'Toko Anda belum memiliki catatan hutang kulakan ke supplier.': 'Your store does not have supplier purchase debt records yet.',
      'Sisa Hutang': 'Remaining Payable',
      'Detail Hutang': 'Payable Details',
      'Riwayat Pembayaran Hutang': 'Payable Payment History',
      'Belum ada pembayaran dicatat untuk hutang ini.': 'No payment recorded for this payable yet.',
      'Bayar Hutang': 'Pay Payable',
      'Hapus Hutang': 'Delete Payable',
      'Hapus Piutang': 'Delete Receivable',
      'Apakah Anda yakin ingin menghapus data hutang ini secara permanen?': 'Are you sure you want to permanently delete this payable?',
      'Apakah Anda yakin ingin menghapus data piutang ini secara permanen?': 'Are you sure you want to permanently delete this receivable?',

      // POS / Kasir
      'Keranjang Belanja': 'Shopping Cart',
      'Keranjang kosong': 'Empty cart',
      'Cari barang berdasarkan barcode atau nama...': 'Search item by barcode or name...',
      'Pilih Pelanggan': 'Select Customer',
      'Diskon Transaksi': 'Transaction Discount',
      'Subtotal': 'Subtotal',
      'Diskon': 'Discount',
      'Pajak (11%)': 'Tax (11%)',
      'Total Belanja': 'Total Purchase',
      'Cara Pembayaran': 'Payment Method',
      'Uang Dibayar': 'Cash Paid',
      'Kembalian': 'Change',
      'Bayar Sekarang': 'Pay Now',
      'Struk Transaksi': 'Transaction Receipt',
      'Cetak Struk': 'Print Receipt',
      'Unduh': 'Download',
      'Unduh PDF': 'Download PDF',
      'Transaksi Baru': 'New Transaction',

      // Cash Sessions
      'Sesi Kasir': 'Cashier Sessions',
      'Kelola saldo awal, akhir, dan mutasi kas dalam laci kasir.': 'Manage starting, ending, and cash movement in the cashier drawer.',
      'Buka Sesi Kasir': 'Open Cashier Session',
      'Tutup Sesi Kasir': 'Close Cashier Session',
      'Sesi Aktif': 'Active Session',
      'Saldo Awal Laci *': 'Starting Drawer Cash *',
      'Masukkan saldo awal kas dalam laci...': 'Enter starting cash in drawer...',
      'Buka Sesi': 'Open Session',
      'Tutup Sesi': 'Close Session',
      'Saldo Akhir Laci Aktual *': 'Actual Ending Drawer Cash *',
      'Masukkan saldo akhir laci kasir fisik...': 'Enter physical cashier drawer ending cash...',
      'Saldo Ekspektasi Sistem': 'System Expected Balance',
      'Selisih Kas': 'Cash Difference',

      // Login
      'Masuk ke Sistem': 'System Login',
      'Silakan login menggunakan akun toko Anda': 'Please log in using your store account',
      'Password': 'Password',
      'Masuk': 'Log In',
      'Login gagal, cek kembali username/password Anda.': 'Login failed, please check your username and password.',

      // Master Data Dynamic / Missing Translations (EN)
      'Ubah Produk': 'Edit Product',
      'Tambah Produk Baru': 'Add New Product',
      'Produk berhasil diubah.': 'Product updated successfully.',
      'Produk baru berhasil ditambahkan.': 'New product added successfully.',
      'Produk berhasil dihapus.': 'Product deleted successfully.',
      'Gagal memuat data produk.': 'Failed to load products.',
      'Gagal memuat detail produk.': 'Failed to load product details.',
      'Gagal menyimpan data produk.': 'Failed to save product data.',
      'Gagal menghapus produk.': 'Failed to delete product.',
      'Terjadi kesalahan sistem saat memuat data.': 'A system error occurred while loading data.',
      'Edit Kategori': 'Edit Category',
      'Apakah Anda yakin ingin menghapus kategori "': 'Are you sure you want to delete category "',
      '"? Tindakan ini tidak dapat dibatalkan.': '"? This action cannot be undone.',
      'Kategori berhasil diperbarui.': 'Category updated successfully.',
      'Kategori berhasil ditambahkan.': 'Category added successfully.',
      'Kategori berhasil dihapus.': 'Category deleted successfully.',
      'Gagal memuat data kategori. Periksa koneksi Anda.': 'Failed to load categories. Please check your connection.',
      'Gagal menyimpan kategori. Coba lagi.': 'Failed to save category. Please try again.',
      'Gagal menghapus kategori. Coba lagi.': 'Failed to delete category. Please try again.',
      'Apakah Anda yakin ingin menghapus satuan ': 'Are you sure you want to delete unit ',
      '?': '?',
      'Satuan berhasil diubah.': 'Unit updated successfully.',
      'Satuan baru berhasil ditambahkan.': 'New unit added successfully.',
      'Satuan berhasil dihapus.': 'Unit deleted successfully.',
      'Gagal memuat data satuan.': 'Failed to load units.',
      'Gagal menyimpan data satuan.': 'Failed to save unit data.',
      'Gagal menghapus satuan.': 'Failed to delete unit.',
      'Apakah Anda yakin ingin menghapus supplier ': 'Are you sure you want to delete supplier ',
      'Supplier berhasil diperbarui.': 'Supplier updated successfully.',
      'Supplier berhasil ditambahkan.': 'Supplier added successfully.',
      'Supplier berhasil dihapus.': 'Supplier deleted successfully.',
      'Gagal memuat data supplier.': 'Failed to load suppliers.',
      'Gagal menyimpan supplier. Coba lagi.': 'Failed to save supplier. Please try again.',
      'Gagal menghapus supplier. Coba lagi.': 'Failed to delete supplier. Please try again.',
      'Hapus pelanggan "': 'Delete customer "',
      'Pelanggan berhasil diperbarui.': 'Customer updated successfully.',
      'Pelanggan berhasil ditambahkan.': 'Customer added successfully.',
      'Pelanggan berhasil dihapus.': 'Customer deleted successfully.',
      'Gagal memuat data pelanggan.': 'Failed to load customers.',
      'Gagal menghapus pelanggan.': 'Failed to delete customer.',
      'Terjadi kesalahan. Silakan coba lagi.': 'An error occurred. Please try again.',
      'Kelola saldo awal, akhir, dan mutasi kas dalam laci kasir untuk setiap giliran kerja (shift).': 'Manage starting, ending, and cash movements in the cashier drawer for each work shift.',
      'Tidak Ada Sesi Aktif': 'No Active Session',
      'Memeriksa sesi kasir...': 'Checking cashier session...',
      'Ekspektasi Kas Laci': 'System Expected Cash',
      'Laci kasir saat ini terkunci. Silakan buka sesi kasir baru untuk memulai transaksi penjualan.': 'The cashier drawer is currently locked. Please open a new cashier session to start sales transactions.',
      'Buka Sesi Kasir Baru': 'Open New Cashier Session',
      'Riwayat Sesi Kasir': 'Cashier Session History',
      'Memuat riwayat sesi...': 'Loading session history...',
      'Belum ada riwayat sesi kasir.': 'No cashier session history yet.',
      'Modal Awal': 'Starting Balance',
      'Kas Aktual': 'Actual Cash',
      'Catatan Pembuka': 'Opening Notes',
      'Catatan Penutup': 'Closing Notes',
      'Membuka Sesi...': 'Opening Session...',
      'Menutup Sesi...': 'Closing Session...',
      'Open': 'Open',
      'Closed': 'Closed',
      'Pantau rekaman riwayat log aktivitas pengguna, perubahan data master, dan aksi audit penting sistem.': 'Monitor user activity logs history, master data changes, and critical system audit actions.',
      'Akses Ditolak': 'Access Denied',
      'Halaman log aktivitas audit hanya diperuntukkan bagi pemilik toko (owner) untuk memantau keamanan sistem.': 'The audit activity log page is reserved for the store owner to monitor system security.',
      'Auth & Sesi': 'Auth & Sessions',
      'Penjualan POS': 'POS Sales',
      'Inventori & Stok': 'Inventory & Stock',
      'aktivitas': 'activities',
      'Memuat log aktivitas...': 'Loading activity logs...',
      'Belum Ada Log Aktivitas': 'No Activity Logs Yet',
      'Aktivitas sistem yang direkam akan ditampilkan di halaman ini.': 'System activities recorded will be displayed on this page.',
      'Aktivitas / Tindakan': 'Activity / Action',
      'Alamat IP': 'IP Address',
      'Objek': 'Object',
      'Periksa': 'Check',
      'Rincian Log Aktivitas': 'Activity Log Details',
      'Detail Log Aktivitas': 'Activity Log Details',
      'Modul / Sektor': 'Module / Sector',
      'Tindakan': 'Action',
      'Perubahan Data': 'Data Changes',
      'Nilai Lama': 'Old Value',
      'Nilai Baru': 'New Value',
      'Auth': 'Auth & Sessions',
      'Product': 'Product',
      'Category': 'Category',
      'Unit': 'Unit',
      'Customer': 'Customer',
      'Sales': 'POS Sales',
      'Purchases': 'Purchases',
      'Expenses': 'Expenses',
      'Inventory': 'Inventory & Stock',
      'CashSession': 'Cashier Session',
      'Settings': 'Store Settings',

      // Payables & Receivables List
      'Belum Bayar': 'Unpaid',
      'Bayar Sebagian': 'Partial',
      'transaksi hutang': 'payable transactions',
      'Memuat data hutang...': 'Loading payables...',
      'Tidak Ada Transaksi Hutang': 'No Payable Transactions',
      'Tidak ditemukan transaksi pembelian kredit (hutang) berdasarkan filter saat ini.': 'No credit purchase transactions (payables) found based on current filters.',
      'No. Hutang': 'Payable No.',
      'Rincian Hutang': 'Payable Details',
      'Catatan Kulakan': 'Stock Notes',
      'Catat Pembayaran': 'Record Payment',
      'Belum ada pembayaran dicatat.': 'No payments recorded yet.',
      'Metode': 'Method',
      'Bayar hutang untuk': 'Pay debt for',
      'Tanggal Pembayaran': 'Payment Date',
      'Nominal Pembayaran': 'Payment Amount',
      'Maksimal pembayaran': 'Maximum payment',
      'Lainnya': 'Other',

      'Piutang Pelanggan': 'Customer Receivables',
      'Semua Pelanggan': 'All Customers',
      'transaksi piutang': 'receivable transactions',
      'Memuat data piutang...': 'Loading receivables...',
      'Tidak Ada Transaksi Piutang': 'No Receivable Transactions',
      'Tidak ditemukan transaksi penjualan kredit (piutang) berdasarkan filter saat ini.': 'No credit sales transactions (receivables) found based on current filters.',
      'No. Piutang': 'Receivable No.',
      'Rincian Piutang': 'Receivable Details',
      'Bayar piutang untuk': 'Pay receivable for',

      // POS / Kasir
      'Kasir / POS': 'Cashier / POS',
      'Memuat barang...': 'Loading items...',
      'Barang tidak ditemukan.': 'Item not found.',
      'Bersihkan': 'Clear',
      'Pelanggan Umum': 'General Customer',
      'Diskon / Potongan (IDR)': 'Discount / Cut (IDR)',
      'Pajak (IDR)': 'Tax (IDR)',
      'Sembunyikan': 'Hide',
      'Tambah Pajak': 'Add Tax',
      'Uang Pas': 'Exact Amount',
      'Kurang Bayar': 'Underpaid',
      'Struk Pembayaran': 'Payment Receipt',
      'Transaksi Sukses': 'Transaction Successful',
      'Tunai Dibayar': 'Cash Paid',

      // Status & Payment Methods (database values -> English)
      'Completed': 'Completed',
      'Voided': 'Voided',
      'Posted': 'Posted',
      'Paid': 'Paid',
      'Unpaid': 'Unpaid',
      'Partial': 'Partial',
      'Cash': 'Cash',
      'Transfer': 'Transfer',
      'QRIS': 'QRIS',
      'DebitCard': 'Debit Card',
      'Other': 'Other',

      // Placeholder
      'Fitur dalam Pengembangan': 'Feature under Development',
      'Fitur ini sedang dalam tahap pengembangan dan akan segera tersedia.': 'This feature is currently under development and will be available soon.',
      // SysAdmin Stores
      'Kelola dan pantau seluruh pendaftaran toko kelontong di dalam platform.': 'Manage and monitor all grocery store registrations on the platform.',
      'Registrasi Toko Baru': 'Register New Store',
      'Cari nama toko, alamat, atau no telepon...': 'Search store name, address, or phone number...',
      'toko': 'stores',
      'Memuat data toko dari server...': 'Loading store data from server...',
      'Toko Tidak Ditemukan': 'Store Not Found',
      'Tidak ada data toko kelontong yang sesuai dengan kata kunci pencarian Anda.': 'No grocery store data matches your search query.',
      'Informasi Toko': 'Store Info',
      'Kontak & Alamat': 'Contact & Address',
      'Tanggal Bergabung': 'Date Joined',
      'Ditangguhkan': 'Suspended',
      'Ubah Profil Toko': 'Edit Store Profile',
      'Tangguhkan Toko': 'Suspend Store',
      'Aktifkan Toko': 'Activate Store',
      'Registrasi Toko & Akun Owner': 'Register Store & Owner Account',
      'Daftarkan profil toko fisik baru sekaligus membuat akun Owner pertama.': 'Register a new physical store profile and create the first Owner account.',
      'Nama Toko': 'Store Name',
      'Nama Toko wajib diisi (Maks. 100 karakter).': 'Store Name is required (Max 100 characters).',
      'No. Telepon Toko': 'Store Phone Number',
      'Valuta / Currency': 'Currency',
      'Zona Waktu / Timezone': 'Timezone',
      'Footer Struk Kasir': 'Receipt Footer',
      'Logo URL (Opsional)': 'Logo URL (Optional)',
      'Informasi Akun Owner': 'Owner Account Info',
      'Nama Lengkap Owner': 'Owner Full Name',
      'Nama Owner wajib diisi.': 'Owner Name is required.',
      'Username Login': 'Username Login',
      'Password Akun': 'Account Password',
      'Simpan & Daftarkan': 'Save & Register',
      'Ubah data identitas toko kelontong terpilih.': 'Edit identity data of the selected grocery store.',
      'Simpan Perubahan': 'Save Changes',
      'Apakah Anda yakin ingin menonaktifkan toko {0}? Semua akun user dari toko ini akan ikut terpengaruh.': 'Are you sure you want to suspend store "{0}"? All user accounts from this store will also be affected.',
      'Apakah Anda yakin ingin mengaktifkan toko {0}? Semua akun user dari toko ini akan ikut terpengaruh.': 'Are you sure you want to activate store "{0}"? All user accounts from this store will also be affected.',
      'Gagal mendaftarkan toko baru.': 'Failed to register new store.',
      'Terjadi kesalahan sistem saat mendaftarkan toko.': 'System error occurred while registering store.',
      'Gagal mengubah status toko.': 'Failed to change store status.',
      'Terjadi kesalahan saat mengubah status toko.': 'Error occurred while changing store status.',
      'Toko berhasil diaktifkan.': 'Store successfully activated.',
      'Toko berhasil dinonaktifkan.': 'Store successfully suspended.',
      'Terjadi kesalahan saat memuat data toko.': 'Error occurred while loading store data.',
      // SysAdmin Dashboard
      'Total Toko Terdaftar': 'Total Registered Stores',
      'Toko': 'Store',
      'Toko Aktif / Nonaktif:': 'Active / Inactive Stores:',
      'Akun Owner Terdaftar': 'Registered Owner Accounts',
      'Estimasi Owner / Toko:': 'Estimated Owner / Store:',
      '1 Owner': '1 Owner',
      'Volume Transaksi Global': 'Global Transaction Volume',
      'Bulan Berjalan:': 'Current Month:',
      'Juni 2026': 'June 2026',
      'Uptime Server & Sistem': 'Server & System Uptime',
      'Status Koneksi DB:': 'DB Connection Status:',
      'Analisis Metrik Platform': 'Platform Metrics Analysis',
      'Grafik pertumbuhan toko, pengguna, dan performa uptime sistem server.': 'Chart of store growth, users, and server system uptime performance.',
      'Performa Sistem': 'System Performance',
      'Toko Baru': 'New Stores',
      '3 pendaftaran retail terbaru.': '3 latest retail registrations.',
      // Users List
      'Kelola seluruh akun Owner dan Admin toko kelontong di platform.': 'Manage all Owner and Admin accounts of grocery stores on the platform.',
      'Kelola akun admin/penjaga untuk toko Anda (Maksimal 3 admin aktif).': 'Manage admin/clerk accounts for your store (Maximum 3 active admins).',
      'User berhasil diperbarui.': 'User updated successfully.',
      'Gagal menyimpan user.': 'Failed to save user.',
      'User berhasil ditambahkan.': 'User added successfully.',
      'Gagal menambahkan user.': 'Failed to add user.',
      'Password berhasil direset.': 'Password reset successfully.',
      'Gagal mereset password.': 'Failed to reset password.',
      'User berhasil dihapus.': 'User deleted successfully.',
      'Gagal menghapus user.': 'Failed to delete user.',
      'Toko ini sudah mencapai batas maksimum 3 admin penjaga aktif.': 'This store has reached the maximum limit of 3 active admin clerks.',
      'User berhasil diaktifkan.': 'User activated successfully.',
      'User berhasil dinonaktifkan.': 'User deactivated successfully.',
      'Gagal mengubah status user.': 'Failed to change user status.',
      'Gagal memuat data pengguna.': 'Failed to load user data.',
      'Gagal memuat daftar toko.': 'Failed to load stores list.',
      // Users List Interface
      'Kelola Pengguna': 'Manage Users',
      'Cari User': 'Search User',
      'Cari nama atau username...': 'Search name or username...',
      'Filter Peran': 'Filter Role',
      'Semua Peran': 'All Roles',
      'Peran': 'Role',
      'Tanggal Dibuat': 'Date Created',
      'Nama Lengkap': 'Full Name',
      'Peran / Hak Akses': 'Role / Access Rights',
      'Penempatan Toko': 'Store Placement',
      'Admin / Penjaga': 'Admin / Clerk',
      'Rasio Keaktifan Toko': 'Active Store Rate',
      'Toko Aktif:': 'Active Stores:',
      'Keaktifan Toko': 'Store Activity',
      'Grafik pertumbuhan toko, pengguna, dan rasio keaktifan toko.': 'Chart of store growth, users, and store activity rate.'
    }
  };

  setLanguage(lang: Language): void {
    localStorage.setItem(this.STORAGE_KEY, lang);
    this.currentLang.set(lang);
  }

  translate(key: string): string {
    const lang = this.currentLang();
    return this.dictionary[lang]?.[key] || key;
  }
}
